#
# Including Makefiles must define TOP_DIR appropriately.
#
# $Id: Makefile.inc,v 1.1 2008/11/22 19:43:25 bschneid Exp bschneid $
#
#
# System-dependent definitions
#
#
RANLIB = ranlib
FULL_DIR = $(MESALIB)/Full_Library
CHRLIB = $(MESALIB)/chrlib.a
CLAMLIB = $(MESALIB)/clamlib.a
BLASLIB = $(MESALIB)/blaslib.a
LAPACKLIB = $(MESALIB)/lapacklib.a
DPINTLIB = $(MESALIB)/dpintlib.a
INTLIB = $(MESALIB)/intlib.a
UTILLIB = $(MESALIB)/utillib.a
IOLIB = $(MESALIB)/iolib.a
MACHLIB = $(MESALIB)/machlib.a
MATHLIB = $(MESALIB)/mathlib.a
SYMLIB = $(MESALIB)/symlib.a
#
