#
# Including Makefiles must define TOP_DIR appropriately.
#
# $Id: Makefile.inc,v 1.1 2008/11/22 19:43:25 bschneid Exp bschneid $
#
#
# System-dependent definitions
#
#
RANLIB = ranlib
FULL_DIR = $(UTILITIES)/Full_Library
CHRLIB = $(UTILITIES)/chrlib.a
CLAMLIB = $(UTILITIES)/clamlib.a
BLASLIB = $(UTILITIES)/blaslib.a
LAPACKLIB = $(UTILITIES)/lapacklib.a
DPINTLIB = $(UTILITIES)/dpintlib.a
INTLIB = $(UTILITIES)/intlib.a
UTILLIB = $(UTILITIES)/utillib.a
IOLIB = $(UTILITIES)/iolib.a
MACHLIB = $(UTILITIES)/machlib.a
MATHLIB = $(UTILITIES)/mathlib.a
SYMLIB = $(UTILITIES)/symlib.a
#
